[package]
name = "koa-rust-router"
version = "0.1.0"
authors = ["moldray <leids@foxmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "koa_rust_router"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
